services:
  dev-db:
    image: postgres:16
    ports:
      - 127.0.0.1:5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: template
    networks:
      - template
    volumes:
      - templateDB:/var/lib/postgresql/data
networks:
  template:
volumes:
  templateDB: