services:
  dev-db:
    image: postgres:15
    ports:
      - 127.0.0.1:5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: mamonDB
    networks:
      - mamon
    volumes:
      - mamonDB:/var/lib/postgresql/data
networks:
  mamon:
volumes:
  mamonDB: